name: good_one_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^18.0.1
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.0.0
  flutter_native_splash: ^2.4.2
  flutter_secure_storage: ^9.2.4
  flutter_stripe: ^11.4.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  latlong2: ^0.9.1
  photo_view: ^0.15.0
  provider: ^6.1.2
  socket_io_client: ^3.0.2
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#f70303"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true
