name: good_one_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ^3.5.4

dependencies:
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^19.3.0
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.0.0
  flutter_native_splash: ^2.4.2
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.4
  flutter_stripe: ^11.4.0
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  photo_view: ^0.15.0
  pinput: ^5.0.1
  provider: ^6.1.2
  socket_io_client: ^3.0.2
  syncfusion_flutter_charts: ^29.1.33
  table_calendar: ^3.1.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon2.png"  
  remove_alpha_ios: true
  adaptive_icon_background: "#f70303"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  
  # Background color
  color: "#f70303"
  
  # Use a square logo image that will appear circular
  image: "assets/images/logo.png"
  
  # Remove branding temporarily to match Android appearance
  # branding: "assets/images/app_name.png"
  
  # iOS specific settings for better control
  ios_content_mode: scaleAspectFit
  
  # Android settings
  android_gravity: center
  android_12:
    color: "#f70303"
    image: "assets/images/logo.png"
    # branding: "assets/images/branding.png"
  
  # Make it fullscreen
  fullscreen: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true