// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV85Arj9faEfmN2KDvu-AUpBRT0xP82DU',
    appId: '1:884659155357:web:284d26e5c29f80ba21bf74',
    messagingSenderId: '884659155357',
    projectId: 'goodone-73cff',
    authDomain: 'goodone-73cff.firebaseapp.com',
    storageBucket: 'goodone-73cff.firebasestorage.app',
    measurementId: 'G-3FPRJBLHB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ7qFFacoi5mIk38NElq18cJIQwd47WWQ',
    appId: '1:884659155357:android:bbc1ebee82af756a21bf74',
    messagingSenderId: '884659155357',
    projectId: 'goodone-73cff',
    storageBucket: 'goodone-73cff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq8GzNOdrTsC3PyRj5X4yuboOmwHQByqk',
    appId: '1:884659155357:ios:414e468269f6e32e21bf74',
    messagingSenderId: '884659155357',
    projectId: 'goodone-73cff',
    storageBucket: 'goodone-73cff.firebasestorage.app',
    iosBundleId: 'com.example.goodOneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq8GzNOdrTsC3PyRj5X4yuboOmwHQByqk',
    appId: '1:884659155357:ios:414e468269f6e32e21bf74',
    messagingSenderId: '884659155357',
    projectId: 'goodone-73cff',
    storageBucket: 'goodone-73cff.firebasestorage.app',
    iosBundleId: 'com.example.goodOneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV85Arj9faEfmN2KDvu-AUpBRT0xP82DU',
    appId: '1:884659155357:web:2674df54310569d721bf74',
    messagingSenderId: '884659155357',
    projectId: 'goodone-73cff',
    authDomain: 'goodone-73cff.firebaseapp.com',
    storageBucket: 'goodone-73cff.firebasestorage.app',
    measurementId: 'G-X08F9W8KT6',
  );
}
